# Generated by Django 2.0 on 2021-03-10 06:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter the answer text that you want displayed', verbose_name='Content')),
                ('feedback_initial', models.TextField(blank=True, verbose_name='Initial Feedback')),
                ('feedback_final', models.TextField(verbose_name='Final Feedback')),
                ('rating_from', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating From')),
                ('rating_to', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating To')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='FeedbackLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_max', models.CharField(max_length=150, verbose_name='Label for maximum level of agreement')),
                ('label_min', models.CharField(max_length=150, verbose_name='Label for minimum level of agreement')),
                ('language', models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('A', 'Arabic'), ('L', 'All'), ('E', 'Russian-in-English'), ('B', 'Arabic-in-Arabic'), ('P', 'Portuguese-in-English'), ('D', 'Portuguese-in-Portuguese')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='JudgmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Judgment Task Description')),
            ],
            options={
                'verbose_name': 'Judgment Task',
                'verbose_name_plural': 'Judgment Tasks',
            },
        ),
        migrations.CreateModel(
            name='LearningObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('objectives', models.TextField(verbose_name='Learning Objectives')),
                ('language', models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('A', 'Arabic'), ('L', 'All'), ('E', 'Russian-in-English'), ('B', 'Arabic-in-Arabic'), ('P', 'Portuguese-in-English'), ('D', 'Portuguese-in-Portuguese')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('module_number', models.IntegerField()),
                ('introduction', models.TextField(blank=True, verbose_name='Module Introduction')),
                ('blurb', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('A', 'Arabic'), ('L', 'All'), ('E', 'Russian-in-English'), ('B', 'Arabic-in-Arabic'), ('P', 'Portuguese-in-English'), ('D', 'Portuguese-in-Portuguese')], max_length=1)),
                ('image_for_topics', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objectives', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='culture_content.LearningObjectives')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('A', 'Arabic'), ('L', 'All'), ('E', 'Russian-in-English'), ('B', 'Arabic-in-Arabic'), ('P', 'Portuguese-in-English'), ('D', 'Portuguese-in-Portuguese'), ('I', 'All-Arabic'), ('O', 'All-Portuguese')], max_length=1)),
                ('type', models.CharField(blank=True, choices=[('I', 'Instructor'), ('S', 'Student')], default='S', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Response')),
                ('responded', models.DateTimeField(default=datetime.datetime.now, max_length=100)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_content.Answer', verbose_name='Options')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, verbose_name='Situation')),
                ('initial_information', models.TextField(blank=True, verbose_name='Context of the Scenario')),
                ('context_after_feedback', models.BooleanField(default=False)),
                ('context_before_and_after_feedback', models.BooleanField(default=False)),
                ('language_note', models.TextField(blank=True, verbose_name='Language Notes')),
                ('culture_note', models.TextField(blank=True, verbose_name='Culture Notes')),
                ('language_note_after_feedback', models.BooleanField(default=False)),
                ('language_note_before_and_after_feedback', models.BooleanField(default=False)),
                ('culture_note_after_feedback', models.BooleanField(default=False)),
                ('culture_note_before_and_after_feedback', models.BooleanField(default=False)),
                ('reflection_task', models.TextField(blank=True, verbose_name='Scenario Reflection Task')),
                ('extension_task', models.TextField(blank=True, verbose_name='Scenario Extension Task')),
                ('order', models.IntegerField(blank=True, default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('judgment_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_content.JudgmentTask')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('activation', models.TextField(blank=True, verbose_name='Schema Activation')),
                ('new_information', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True, verbose_name='Reflection Task')),
                ('roleplay', models.TextField(blank=True, verbose_name='Roleplay Task')),
                ('extension', models.TextField(blank=True, verbose_name='Extension Task')),
                ('language', models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('A', 'Arabic'), ('L', 'All'), ('E', 'Russian-in-English'), ('B', 'Arabic-in-Arabic'), ('P', 'Portuguese-in-English'), ('D', 'Portuguese-in-Portuguese')], max_length=1)),
                ('order', models.IntegerField(blank=True, default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objectives', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='culture_content.LearningObjectives')),
                ('scenarios', models.ManyToManyField(to='culture_content.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='topics',
            field=models.ManyToManyField(to='culture_content.Topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_content.JudgmentTask', verbose_name='Judgement Task'),
        ),
    ]
