# Generated by Django 2.0 on 2021-03-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
    ]
