# Generated by Django 2.0 on 2021-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0002_remove_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
